import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ data }) {
  data;
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img></img>
          <a href="/">Home</a>
          <a href="/events-page">Events</a>
          <a href="/about-us">About us</a>
        </nav>
      </header>
      <main className="main">
        {data.map((e) => {
          return (
            <div key={e.id} className="event-card">
              <Link href={`/events-page/${e.id}`} passHref>
                <img
                  src={e.image}
                  className="event-img"
                  alt={e.title}
                  width={200}
                  height={250}
                ></img>
                <h2 className="event-title">Events in {e.title}</h2>
                <p className="event-paragraph">{e.description}</p>
              </Link>
            </div>
          );
        })}
      </main>
      <footer></footer>
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import('../../data/data.json');

  return {
    props: {
      data: events_categories,
    },
  };
}
